database:
  url: "postgres://helix_user:helix_pass@postgres:5432/helix_db"

redis:
  url: "redis://redis:6379/1"

rabbitmq:
  url: "amqp://helix_user:helix_pass@rabbitmq:5672//"


logging:
  level: "INFO"
  file: "/app/logs/helix.log"

features:
  enable_celery: true
  enable_llm: true
